"use client";
import { useCallback,useEffect,useMemo,useState } from "react";
import { Alert,Badge,Button,Select,useToast } from "@/components";
import { createAuthApi } from "./api";
import { useAuth } from "./auth-provider";
import type { AuditLog,TeamInvitation,TeamMember,TeamRole } from "./types";
import styles from "./team-page.module.css";

const ROLE_OPTIONS=[{value:"owner",label:"所有者"},{value:"admin",label:"管理员"},{value:"engineer",label:"工程师"},{value:"viewer",label:"查看者"}];
export function TeamPage(){const api=useMemo(()=>createAuthApi(),[]);const {identity,hasPermission,refresh}=useAuth();const {toast}=useToast();const team=identity?.teams.find(item=>item.id===identity.active_team_id);
 const [members,setMembers]=useState<TeamMember[]>([]);const [invitations,setInvitations]=useState<TeamInvitation[]>([]);const [logs,setLogs]=useState<AuditLog[]>([]);const [email,setEmail]=useState("");const [role,setRole]=useState<TeamRole>("engineer");const [error,setError]=useState("");const [latestToken,setLatestToken]=useState("");
 const load=useCallback(async()=>{if(!team)return;setError("");try{const requests:[Promise<TeamMember[]>,Promise<TeamInvitation[]|null>,Promise<AuditLog[]|null>]=[api.listMembers(team.id),hasPermission("team.members.manage")?api.listInvitations(team.id):Promise.resolve(null),hasPermission("team.audit.read")?api.listAuditLogs(team.id):Promise.resolve(null)];const [m,i,a]=await Promise.all(requests);setMembers(m);setInvitations(i??[]);setLogs(a??[]);}catch(reason){setError(reason instanceof Error?reason.message:"团队数据读取失败。");}},[api,hasPermission,team]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);if(!team)return null;
 const add=async()=>{try{const item=await api.addMember(team.id,email,role);setMembers(items=>[...items.filter(x=>x.user_id!==item.user_id),item]);setEmail("");toast({title:"团队成员已加入",tone:"success"});await refresh();}catch(reason){setError(reason instanceof Error?reason.message:"添加失败。");}};
 const invite=async()=>{try{const item=await api.createInvitation(team.id,email,role);setInvitations(items=>[item,...items]);setLatestToken(item.accept_token??"");setEmail("");toast({title:"邀请已创建",description:"请安全地把一次性口令发送给受邀用户。",tone:"success"});}catch(reason){setError(reason instanceof Error?reason.message:"邀请创建失败。");}};
 const update=async(userId:string,nextRole:TeamRole)=>{try{const item=await api.updateMemberRole(team.id,userId,nextRole);setMembers(items=>items.map(x=>x.user_id===userId?item:x));toast({title:"成员角色已更新",tone:"success"});}catch(reason){setError(reason instanceof Error?reason.message:"角色更新失败。");}};
 const remove=async(userId:string)=>{if(!confirm("确认移除该团队成员吗？"))return;try{await api.removeMember(team.id,userId);setMembers(items=>items.filter(x=>x.user_id!==userId));toast({title:"成员已移除",tone:"success"});}catch(reason){setError(reason instanceof Error?reason.message:"移除失败。");}};
 return <div className={styles.root}><section className={styles.hero}><div><span>TEAM & SERVER AUTHORIZATION</span><h1>{team.name}</h1><p>当前角色：{team.role} · 服务端按团队上下文验证每一次项目和记录操作。</p></div><Badge tone="team">{team.member_count}名成员</Badge></section>{error?<Alert tone="error" title="团队权限提示">{error}</Alert>:null}
 <div className={styles.grid}><section className={styles.section}><h2>团队成员</h2>{hasPermission("team.members.manage")?<div className={styles.toolbar}><input className={styles.input} value={email} onChange={e=>setEmail(e.target.value)} placeholder="成员邮箱"/><Select value={role} onChange={e=>setRole(e.target.value as TeamRole)} options={ROLE_OPTIONS}/><div><Button size="sm" variant="primary" onClick={()=>void add()} disabled={!email}>直接加入</Button> <Button size="sm" variant="secondary" onClick={()=>void invite()} disabled={!email}>创建邀请</Button></div></div>:null}
 {members.map(member=><div className={styles.member} key={member.user_id}><div><strong>{member.display_name}</strong><p>{member.email}</p></div>{hasPermission("team.members.manage")?<Select value={member.role} onChange={e=>void update(member.user_id,e.target.value as TeamRole)} options={ROLE_OPTIONS}/>:<Badge tone="neutral">{member.role}</Badge>}{hasPermission("team.members.manage")?<Button size="sm" variant="danger" onClick={()=>void remove(member.user_id)}>移除</Button>:null}</div>)}</section>
 <section className={styles.section}><h2>待处理邀请</h2>{latestToken?<Alert tone="warning" title="一次性邀请口令"><div className={styles.token}>{latestToken}</div></Alert>:null}{invitations.length?invitations.map(item=><div className={styles.invite} key={item.id}><strong>{item.email}</strong><p><Badge tone={item.status==="pending"?"warning":"neutral"}>{item.status}</Badge> · {item.role}</p><small>有效至 {new Date(item.expires_at).toLocaleString("zh-CN")}</small></div>):<p>暂无邀请。</p>}</section></div>
 {hasPermission("team.audit.read")?<section className={styles.section}><h2>授权审计</h2>{logs.slice(0,20).map(log=><div className={styles.audit} key={log.id}><strong>{log.action}</strong> · {log.actor_display_name??"系统"} · {new Date(log.created_at).toLocaleString("zh-CN")}</div>)}</section>:null}</div>}
