import type { ToolCategory, ToolDefinition, ToolDiscipline } from "./types";

export const TOOL_DISCIPLINES: Array<{
  id: ToolDiscipline;
  label: string;
  description: string;
}> = [
  { id: "all", label: "全部工具", description: "跨专业工具与知识能力" },
  { id: "mineral-processing", label: "选矿工程", description: "破碎、磨矿、浮选、浓密与冶金" },
  { id: "mining", label: "采矿工程", description: "爆破、运输、通风与生产组织" },
  { id: "automation", label: "自动化", description: "控制、仪表、PLC与工业数据" },
  { id: "electrical", label: "电气工程", description: "负荷、短路、配电与无功补偿" },
  { id: "equipment", label: "设备工程", description: "泵、输送与设备资料" },
  { id: "civil", label: "土建工程", description: "荷载、基础与工业建筑" },
  { id: "general", label: "通用工程", description: "单位换算、数据与报告" },
];

export const TOOL_CATEGORY_LABELS: Record<ToolCategory, string> = {
  calculation: "工程计算",
  analysis: "高级分析",
  design: "方案设计",
  selection: "设备选型",
  simulation: "仿真与控制",
  knowledge: "知识与资料",
};

export const TOOL_CATALOG: ToolDefinition[] = [
  {
    id: "dry-solids-rate",
    slug: "dry-solids-rate",
    name: "干固体量计算",
    description: "根据矿浆体积流量、密度和固体质量分数计算矿浆质量流量、干固体量与水量。",
    discipline: "mineral-processing",
    category: "calculation",
    tags: ["矿浆", "干固体", "流量", "质量平衡"],
    accessLevel: "free",
    status: "VALIDATED",
    availability: "available",
    version: "1.0.0",
    updatedAt: "2026-07-14",
    icon: "calculator",
    featured: true,
    popularity: 100,
  },
  {
    id: "slurry-density-conversion",
    slug: "slurry-density-conversion",
    name: "矿浆密度与浓度换算",
    description: "在矿浆密度、固体密度、质量浓度和体积浓度之间进行一致性换算。",
    discipline: "mineral-processing",
    category: "calculation",
    tags: ["密度", "浓度", "矿浆", "换算"],
    accessLevel: "free",
    status: "VALIDATED",
    availability: "available",
    version: "1.0.0",
    updatedAt: "2026-07-14",
    icon: "droplets",
    featured: true,
    popularity: 92,
  },
  {
    id: "water-balance",
    slug: "water-balance",
    name: "选厂水量平衡",
    description: "核算新水、回水、产品带水、蒸发损失和各工艺节点用水量。",
    discipline: "mineral-processing",
    category: "analysis",
    tags: ["水量平衡", "回水", "浓密", "尾矿"],
    accessLevel: "professional",
    status: "REVIEWING",
    availability: "preview",
    version: "0.6.0",
    updatedAt: "2026-07-10",
    icon: "droplets",
    featured: true,
    popularity: 88,
  },
  {
    id: "metal-balance",
    slug: "metal-balance",
    name: "全流程物料与金属平衡",
    description: "连接多工艺节点，计算固体、水量、品位、金属量、回收率和闭合误差。",
    discipline: "mineral-processing",
    category: "analysis",
    tags: ["物料平衡", "金属平衡", "品位", "回收率"],
    accessLevel: "professional",
    status: "REVIEWING",
    availability: "preview",
    version: "0.5.0",
    updatedAt: "2026-07-13",
    icon: "workflow",
    featured: true,
    popularity: 98,
  },
  {
    id: "grinding-circulating-load",
    slug: "grinding-circulating-load",
    name: "磨矿分级循环负荷",
    description: "按给矿、返砂和溢流数据计算循环负荷、分级效率与工况敏感性。",
    discipline: "mineral-processing",
    category: "calculation",
    tags: ["磨矿", "分级", "循环负荷", "旋流器"],
    accessLevel: "professional",
    status: "VALIDATED",
    availability: "preview",
    version: "1.1.0",
    updatedAt: "2026-07-09",
    icon: "chart",
    popularity: 82,
  },
  {
    id: "flotation-reagent-dosage",
    slug: "flotation-reagent-dosage",
    name: "浮选药剂单耗与加药量",
    description: "根据干矿量和药剂制度计算各加药点瞬时流量、班耗与日耗。",
    discipline: "mineral-processing",
    category: "calculation",
    tags: ["浮选", "药剂", "单耗", "加药"],
    accessLevel: "free",
    status: "REVIEWING",
    availability: "preview",
    version: "0.8.0",
    updatedAt: "2026-07-08",
    icon: "flask",
    popularity: 78,
  },
  {
    id: "cyclone-selection",
    slug: "cyclone-selection",
    name: "水力旋流器初步选型",
    description: "依据处理量、给矿浓度、压力和目标切割粒度进行旋流器组初步配置。",
    discipline: "mineral-processing",
    category: "selection",
    tags: ["旋流器", "分级", "选型", "压力"],
    accessLevel: "professional",
    status: "REVIEWING",
    availability: "planned",
    version: "0.3.0",
    updatedAt: "2026-07-05",
    icon: "gauge",
    popularity: 72,
  },
  {
    id: "thickener-area",
    slug: "thickener-area",
    name: "浓密机面积初算",
    description: "按单位面积处理量、沉降试验数据和目标底流浓度进行面积初算。",
    discipline: "mineral-processing",
    category: "selection",
    tags: ["浓密机", "沉降", "底流", "选型"],
    accessLevel: "professional",
    status: "DRAFT",
    availability: "planned",
    version: "0.2.0",
    updatedAt: "2026-07-03",
    icon: "scale",
    popularity: 65,
  },
  {
    id: "pid-tuning-simulator",
    slug: "pid-tuning-simulator",
    name: "PID参数仿真与整定练习",
    description: "调整比例、积分和微分参数，观察过程响应、超调和稳定时间。",
    discipline: "automation",
    category: "simulation",
    tags: ["PID", "控制", "仿真", "整定"],
    accessLevel: "free",
    status: "VALIDATED",
    availability: "preview",
    version: "1.0.0",
    updatedAt: "2026-07-11",
    icon: "gauge",
    featured: true,
    popularity: 94,
  },
  {
    id: "analog-scaling",
    slug: "analog-scaling",
    name: "模拟量缩放与反算",
    description: "完成PLC原始值、工程量、4～20mA信号和报警阈值之间的转换。",
    discipline: "automation",
    category: "calculation",
    tags: ["PLC", "模拟量", "4-20mA", "缩放"],
    accessLevel: "free",
    status: "VALIDATED",
    availability: "preview",
    version: "1.0.0",
    updatedAt: "2026-07-10",
    icon: "cpu",
    popularity: 91,
  },
  {
    id: "instrument-selection",
    slug: "instrument-selection",
    name: "选矿仪表选型助手",
    description: "按介质、管径、压力、温度和安装条件筛选流量、密度、液位和压力仪表。",
    discipline: "automation",
    category: "selection",
    tags: ["仪表", "选型", "流量计", "液位计"],
    accessLevel: "professional",
    status: "REVIEWING",
    availability: "preview",
    version: "0.7.0",
    updatedAt: "2026-07-07",
    icon: "settings",
    popularity: 84,
  },
  {
    id: "automation-scheme",
    slug: "automation-scheme",
    name: "自动化方案生成",
    description: "根据工艺设备、控制目标和仪表需求生成控制策略、I/O清单与方案框架。",
    discipline: "automation",
    category: "design",
    tags: ["自动化方案", "控制策略", "I/O", "仪表"],
    accessLevel: "team",
    status: "REVIEWING",
    availability: "planned",
    version: "0.4.0",
    updatedAt: "2026-07-06",
    icon: "workflow",
    popularity: 90,
  },
  {
    id: "electrical-load",
    slug: "electrical-load",
    name: "用电负荷计算",
    description: "按设备容量、需要系数、同时系数和功率因数计算有功、无功及视在负荷。",
    discipline: "electrical",
    category: "calculation",
    tags: ["负荷计算", "功率", "需要系数", "配电"],
    accessLevel: "free",
    status: "VALIDATED",
    availability: "preview",
    version: "1.0.0",
    updatedAt: "2026-07-09",
    icon: "zap",
    popularity: 86,
  },
  {
    id: "cable-voltage-drop",
    slug: "cable-voltage-drop",
    name: "电缆压降计算",
    description: "计算三相和单相回路压降、损耗及末端电压，并检查工程限值。",
    discipline: "electrical",
    category: "calculation",
    tags: ["电缆", "压降", "电流", "配电"],
    accessLevel: "free",
    status: "VALIDATED",
    availability: "preview",
    version: "1.0.0",
    updatedAt: "2026-07-08",
    icon: "cable",
    popularity: 83,
  },
  {
    id: "short-circuit-current",
    slug: "short-circuit-current",
    name: "短路电流初步计算",
    description: "按电源、变压器和线路阻抗计算关键节点三相短路电流。",
    discipline: "electrical",
    category: "analysis",
    tags: ["短路电流", "阻抗", "变压器", "保护"],
    accessLevel: "professional",
    status: "REVIEWING",
    availability: "planned",
    version: "0.5.0",
    updatedAt: "2026-07-04",
    icon: "zap",
    popularity: 76,
  },
  {
    id: "belt-conveyor-capacity",
    slug: "belt-conveyor-capacity",
    name: "带式输送机能力校核",
    description: "依据带宽、带速、堆积角和物料密度计算理论输送能力与负荷率。",
    discipline: "equipment",
    category: "calculation",
    tags: ["皮带机", "输送能力", "带速", "物料"],
    accessLevel: "free",
    status: "VALIDATED",
    availability: "preview",
    version: "1.0.0",
    updatedAt: "2026-07-08",
    icon: "conveyor",
    popularity: 80,
  },
  {
    id: "pump-duty-point",
    slug: "pump-duty-point",
    name: "矿浆泵工况点校核",
    description: "根据流量、扬程、管路损失和矿浆修正进行泵工况点快速复核。",
    discipline: "equipment",
    category: "selection",
    tags: ["矿浆泵", "扬程", "管损", "选型"],
    accessLevel: "professional",
    status: "REVIEWING",
    availability: "planned",
    version: "0.4.0",
    updatedAt: "2026-07-06",
    icon: "pump",
    popularity: 79,
  },
  {
    id: "equipment-library",
    slug: "equipment-library",
    name: "选矿设备资料库",
    description: "按工艺和设备类型查询结构、用途、参数、控制点和维护要点。",
    discipline: "equipment",
    category: "knowledge",
    tags: ["设备库", "参数", "结构", "维护"],
    accessLevel: "free",
    status: "REVIEWING",
    availability: "preview",
    version: "0.6.0",
    updatedAt: "2026-07-07",
    icon: "database",
    popularity: 87,
  },
  {
    id: "blasting-charge",
    slug: "blasting-charge",
    name: "台阶爆破装药量估算",
    description: "按孔径、孔深、孔网参数和单耗估算单孔装药量与爆破方量。",
    discipline: "mining",
    category: "calculation",
    tags: ["爆破", "装药量", "孔网", "台阶"],
    accessLevel: "free",
    status: "TEACHING",
    availability: "preview",
    version: "0.7.0",
    updatedAt: "2026-07-02",
    icon: "mountain",
    popularity: 67,
  },
  {
    id: "mine-ventilation",
    slug: "mine-ventilation",
    name: "矿井通风量初算",
    description: "按人员、设备、爆破和最低风速要求计算作业区域需风量。",
    discipline: "mining",
    category: "calculation",
    tags: ["通风", "风量", "矿井", "安全"],
    accessLevel: "professional",
    status: "REVIEWING",
    availability: "planned",
    version: "0.3.0",
    updatedAt: "2026-07-01",
    icon: "wind",
    popularity: 70,
  },
  {
    id: "foundation-load-check",
    slug: "foundation-load-check",
    name: "设备基础荷载快速复核",
    description: "汇总设备静载、动载和维护荷载，形成基础设计输入清单。",
    discipline: "civil",
    category: "calculation",
    tags: ["设备基础", "荷载", "土建", "结构"],
    accessLevel: "professional",
    status: "DRAFT",
    availability: "planned",
    version: "0.2.0",
    updatedAt: "2026-06-30",
    icon: "building",
    popularity: 52,
  },
  {
    id: "engineering-unit-converter",
    slug: "engineering-unit-converter",
    name: "矿业工程单位换算",
    description: "统一流量、密度、压力、品位、功率、长度和质量等常用工程单位。",
    discipline: "general",
    category: "calculation",
    tags: ["单位换算", "流量", "密度", "压力"],
    accessLevel: "free",
    status: "VALIDATED",
    availability: "preview",
    version: "1.0.0",
    updatedAt: "2026-07-12",
    icon: "scale",
    featured: true,
    popularity: 96,
  },
  {
    id: "project-data-template",
    slug: "project-data-template",
    name: "项目数据模板生成",
    description: "按专业生成基础参数、设备、仪表和计算输入模板，便于统一项目数据。",
    discipline: "general",
    category: "design",
    tags: ["项目模板", "数据", "Excel", "协作"],
    accessLevel: "team",
    status: "DRAFT",
    availability: "planned",
    version: "0.2.0",
    updatedAt: "2026-07-01",
    icon: "database",
    popularity: 62,
  },
  {
    id: "engineering-knowledge-search",
    slug: "engineering-knowledge-search",
    name: "矿业工程知识检索",
    description: "跨工具、规范、设备资料和项目知识进行结构化检索与引用。",
    discipline: "general",
    category: "knowledge",
    tags: ["知识库", "检索", "规范", "资料"],
    accessLevel: "professional",
    status: "REVIEWING",
    availability: "planned",
    version: "0.3.0",
    updatedAt: "2026-07-04",
    icon: "book",
    popularity: 85,
  },
];

export function getToolBySlug(slug: string): ToolDefinition | undefined {
  return TOOL_CATALOG.find((tool) => tool.slug === slug);
}

export function getToolById(id: string): ToolDefinition | undefined {
  return TOOL_CATALOG.find((tool) => tool.id === id);
}
