"use client";
import Link from "next/link";
import { useCallback,useEffect,useMemo,useState } from "react";
import { Alert,Badge,Button,Select,useToast } from "@/components";
import { useAuth } from "@/features/auth/auth-provider";
import { createCalculationHistoryApi } from "./api";
import type { ProjectMember,ProjectRole,ProjectSummary } from "./types";
import styles from "./project-detail-page.module.css";

const ROLE_OPTIONS=[{value:"manager",label:"项目经理"},{value:"editor",label:"编辑者"},{value:"viewer",label:"查看者"}];
export function ProjectDetailPage({projectId}:{projectId:string}){const api=useMemo(()=>createCalculationHistoryApi(),[]);const {toast}=useToast();const {identity}=useAuth();const [project,setProject]=useState<ProjectSummary|null>(null);const [members,setMembers]=useState<ProjectMember[]>([]);const [email,setEmail]=useState("");const [role,setRole]=useState<Exclude<ProjectRole,"owner">>("editor");const [error,setError]=useState("");
 const load=useCallback(async()=>{setError("");try{const [p,m]=await Promise.all([api.getProject(projectId),api.listProjectMembers(projectId)]);setProject(p);setMembers(m);}catch(reason){setError(reason instanceof Error?reason.message:"项目读取失败。");}},[api,projectId]);useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
 const canManage=project?.my_role==="owner"||project?.my_role==="manager"||identity?.permissions.includes("project.members.manage");
 const add=async()=>{try{const item=await api.addProjectMember(projectId,email,role);setMembers(items=>[...items.filter(x=>x.user_id!==item.user_id),item]);setEmail("");toast({title:"项目成员已添加",tone:"success"});}catch(reason){setError(reason instanceof Error?reason.message:"添加失败。");}};
 const update=async(userId:string,nextRole:Exclude<ProjectRole,"owner">)=>{try{const item=await api.updateProjectMember(projectId,userId,nextRole);setMembers(items=>items.map(x=>x.user_id===userId?item:x));toast({title:"项目角色已更新",tone:"success"});}catch(reason){setError(reason instanceof Error?reason.message:"更新失败。");}};
 const remove=async(userId:string)=>{if(!confirm("确认移除该项目成员吗？"))return;try{await api.removeProjectMember(projectId,userId);setMembers(items=>items.filter(x=>x.user_id!==userId));toast({title:"项目成员已移除",tone:"success"});}catch(reason){setError(reason instanceof Error?reason.message:"移除失败。");}};
 if(error&&!project)return <Alert tone="error" title="项目不可访问">{error}</Alert>;if(!project)return <p>正在加载项目…</p>;
 return <div className={styles.root}><section className={styles.hero}><div><span>PROJECT AUTHORIZATION</span><h1>{project.name}</h1><p>{project.description||"暂无项目说明"}</p><div className={styles.meta}><Badge tone="brand">{project.code||"未设置编号"}</Badge><Badge tone="team">{project.my_role||"无角色"}</Badge><Badge tone="neutral">{project.visibility==="team"?"团队可见":"私有项目"}</Badge></div></div><div className={styles.actions}><Link href={{pathname:"/history",query:{project_id:project.id}}}><Button variant="secondary">计算记录</Button></Link><Link href="/projects"><Button>返回项目</Button></Link></div></section>{error?<Alert tone="error" title="成员操作失败">{error}</Alert>:null}<section className={styles.section}><h2>项目成员</h2>{canManage?<div className={styles.toolbar}><input className={styles.input} value={email} onChange={e=>setEmail(e.target.value)} placeholder="已加入团队的用户邮箱"/><Select value={role} onChange={e=>setRole(e.target.value as Exclude<ProjectRole,"owner">)} options={ROLE_OPTIONS}/><Button variant="primary" onClick={()=>void add()} disabled={!email}>添加成员</Button></div>:null}{members.map(member=><div className={styles.member} key={member.user_id}><div><strong>{member.display_name}</strong><p>{member.email}</p></div>{member.role==="owner"?<Badge tone="team">项目所有者</Badge>:canManage?<Select value={member.role} onChange={e=>void update(member.user_id,e.target.value as Exclude<ProjectRole,"owner">)} options={ROLE_OPTIONS}/>:<Badge tone="neutral">{member.role}</Badge>}{canManage&&member.role!=="owner"?<Button size="sm" variant="danger" onClick={()=>void remove(member.user_id)}>移除</Button>:null}</div>)}</section></div>}
